export const Sections = [
  {
    name: 'Seccion I',
    cities: [
      'Campana',
      'Escobar',
      'General Las Heras',
      'General Rodríguez',
      'General San Martín',
      'Hurlingham',
      'Ituzaingó',
      'José C. Paz',
      'Luján',
      'Malvinas Argentinas',
      'Marcos Paz',
      'Mercedes',
      'Merlo',
      'Moreno',
      'Morón',
      'Navarro',
      'Pilar',
      'San Fernando',
      'San Isidro',
      'San Miguel',
      'Suipacha',
      'Tigre',
      'Tres de Febrero',
      'Vicente López',
      'Zárate',
    ],
  },
  {
    name: 'Seccion II',
    cities: [
      'Baradero',
      'Capitán Sarmiento',
      'Carmen de Areco',
      'Colón',
      'Exaltación de la Cruz',
      'Pergamino',
      'Ramallo',
      'Rojas',
      'San Andrés de Giles',
      'San Antonio de Areco',
      'San Nicolás',
      'San Pedro',
      'Salto',
      'Zárate',
      'Arrecifes',
    ],
  },
  {
    name: 'Seccion III',
    cities: [
      'Almirante Brown',
      'Avellaneda',
      'Berazategui',
      'Berisso',
      'Brandsen',
      'Cañuelas',
      'Ensenada',
      'Esteban Echeverría',
      'Ezeiza',
      'Florencio Varela',
      'La Matanza',
      'Lanús',
      'Lomas de Zamora',
      'Magdalena',
      'Presidente Perón',
      'Quilmes',
      'San Vicente',
      'Punta indio',
    ],
  },
  {
    name: 'Seccion IV',
    cities: [
      'Alberdi',
      'Bragado',
      'Carlos Casares',
      'Carlos Tejedor',
      'Chacabuco',
      'Chivilcoy',
      'Florentino Ameghino',
      'General Arenales',
      'General Pinto',
      'General Viamonte',
      'General Villegas',
      'Hipólito Yrigoyen',
      'Junín',
      'Leandro N. Alem',
      'Lincoln',
      'Nueve de Julio',
      'Pehuajó',
      'Pellegrini',
      'Rivadavia',
    ],
  },
  {
    name: 'Seccion V',
    cities: [
      'Ayacucho',
      'Balcarce',
      'Castelli',
      'Chascomús',
      'Dolores',
      'General Alvarado',
      'General Belgrano',
      'General Guido',
      'General Lavalle',
      'General Madariaga',
      'General Paz',
      'General Pueyrredón',
      'General Viamonte',
      'La Costa',
      'Las Flores',
      'Lezama',
      'Lobería',
      'Maipú',
      'Mar Chiquita',
      'Monte',
      'Necochea',
      'Pila',
      'Pinamar',
      'Rauch',
      'San Cayetano',
      'Tandil',
      'Tordillo',
      'Villa Gesell',
    ],
  },
  {
    name: 'Seccion VI',
    cities: [
      'Adolfo Alsina',
      'Adolfo Gonzales Chaves',
      'Bahía Blanca',
      'Coronel Dorrego',
      'Coronel Pringles',
      'Coronel Rosales',
      'Coronel Suárez',
      'Daireaux',
      'Gral. Lamadrid',
      'Gral. La Madrid',
    ],
  },
  {
    name: 'Seccion VII',
    cities: [
      'Azul',
      'Bolívar',
      'Gral. Alvear',
      'Olavarría',
      'Roque Pérez',
      'Saladillo',
      'Tapalqué',
      '25 de Mayo',
    ],
  },
  {
    name: 'Seccion VIII',
    cities: ['La Plata'],
  },
];

export const Elections = [
  {
    name: 'PASO 2019 - Fuerza Ganadora',
    field: 'paso2019_pres_ganador',
    percent: 'paso2019_pres_porcentaje_ganador',
  },
  {
    name: 'PASO 2019 - Fuerza 2',
    field: 'paso2019_pres_fuerza2',
    percent: 'paso2019_pres_porcentaje_ganador',
  },
  {
    name: 'Gral. 2019 - Fuerza Ganadora',
    field: 'general2019_pres_ganador',
    percent: 'general2019_pres_porcentaje_ganador',
  },
  {
    name: 'Gral. 2019 - Fuerza 2',
    field: 'general2019_pres_fuerza2',
    percent: 'general2019_pres_porcentaje_ganador',
  },
  {
    name: 'PASO 2023 - Fuerza Ganadora',
    field: 'paso2023_pres_ganador',
    percent: 'paso2023_pres_porcentaje_ganador',
  },
  {
    name: 'PASO 2023 - Fuerza 2',
    field: 'paso2023_pres_fuerza2',
    percent: 'paso2023_pres_porcentaje_ganador',
  },
];
